export const CREATE_DEPARTMENT_TYPE = "CREATE_DEPARTMENT_TYPE";
export const GET_DEPARTMENT_TYPE = "GET_DEPARTMENT_TYPE";
export const UPDATE_DEPARTMENT_TYPE = "UPDATE_DEPARTMENT_TYPE";
export const DELETE_DEPARTMENT_TYPE = "DELETE_DEPARTMENT_TYPE";

export const CREATE_WORKING_HOUR = "CREATE_WORKING_HOUR";
export const GET_WORKING_HOUR = "GET_WORKING_HOUR";
export const UPDATE_WORKING_HOUR = "UPDATE_WORKING_HOUR";
export const DELETE_WORKING_HOUR = "DELETE_WORKING_HOUR";
